### ISSUE TITLE
Test for invalid configurations and input files

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO#225] opened 2023-12-04 13:02 UTC
We should more extensively test the behavior when diverging from the happy path.

Here the error messages should be descriptive for a user to solve the problem

**Comment by fengelniederhammer** [comment] 2023-12-04 13:21
Mind https://github.com/GenSpectrum/LAPIS-SILO/pull/215#discussion_r1413702056 and improve log messages

**Comment by fengelniederhammer** [comment] 2024-03-13 09:28
duplicate of #129

**Closed by fengelniederhammer** 2024-03-13 09:28 UTC
