### ISSUE TITLE
Allow pango aliases to start after flexible number of dots, not necessarily three

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS-SILO#435] opened 2024-05-20 23:14 UTC
Mpox pango aliases after two dots: so B.1.1 = C, and A.1.1 = B

For influenza, the system now uses flexible aliasing, so sometimes F = B.1.2.3.4, whereas G = B.1.2.3.4.5.6

It would be nice if SILO (and LAPIS) supported those more flexible interpretations of pango.

Currently, when you specify such an alias file, you get errors like:

```
{"instance":"lapisClient","level":"info","message":"Request failed with status code 500: Error from SILO: vector::_M_range_check: __n (which is 33) >= this->size() (which is 32)","timestamp":"2024-05-20T23:15:24.869Z"}
```

**Comment by chaoran-chen** [comment] 2024-05-21 00:44
Is there a specification and/or reference implementation for mpox or influenza?

**Comment by Taepper** [comment] 2024-05-23 09:58
Oh oh, the error is definitely a bug.

**Comment by fengelniederhammer** [comment] 2024-10-02 09:12
This is mostly a duplicate of #458 (which specifies a solution that should solve the issue mentioned here).

**Closed by fengelniederhammer** 2024-10-02 09:12 UTC
Labels: loculus
